### PR TITLE
Better text wrap position

### PR DESCRIPTION
**Pull request by SrdjanMilic**
Better text wrap behavior when scaled. More pleasant to the eye (better looking).

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thanks! Any chance of getting a before/after screenshot?

**Comment by SrdjanMilic** [comment]
Hello Michael. No problem.  

Before:  
Screenshot from 2023-07-20 07-27-29

Screenshot from 2023-07-20 07-33-18

After:
Screenshot from 2023-07-20 07-34-48

Screenshot from 2023-07-20 07-34-21

**Comment by SrdjanMilic** [comment]
This and other one PR are just sort of test PR's.  
Next I wold like to replace `tslint` with `eslint` since tslint is deprecated long time ago. Please take a look at: https://palantir.github.io/tslint/

**Comment by michaelbromley** [comment]
Thanks! Yes, replacing tslint would be a huge help 🙏

**Pull request merged**
