### PR TITLE
Embedded video in product description fixed

### PR DESCRIPTION
**Pull request by Mizan3050**
embedded video on product detail description fixed. Created a pipe that returns SafeHtml that is binded to innerHTML.
Screenshot 2023-04-14 at 6 01 05 PM

### CODE REVIEW

**Comment by michaelbromley** [comment]
Thank you for your contribution! 🥳

**Comment by ashishkpaul** [comment]
Thanks for fixing it

**Comment by ashishkpaul** [comment]
Hello sir, Video is playing on the storefront but not able to edit the embedded video code in dashboard

Screenshot_2023-04-16_10-01-03

**Comment by ashishkpaul** [comment]
Edit embedded code icon visible by just leaving the first row
visible by keeping first row empty

**Comment by Mizan3050** [comment]
> Edit embedded code icon visible by just leaving the first row visible by keeping first row empty

Hi, you will have to tap on that video and press backspace/delete.

**Comment by ashishkpaul** [comment]
Sir, I am taking to edit the embedded code, I am able to delete the video
by pressing backspace button

**Comment by ashishkpaul** [comment]
please watch the video
https://user-images.githubusercontent.com/16308863/232321118-0b24c9f8-256e-4cfb-9c45-810cc8004a8b.mp4

**Pull request merged**
